language: python
python: 3.9
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
script: pytest -p no:warnings tests -v --color=yes --exitfirst --showlocals --durations=5 
